import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/main/Navbar";
import Footer from "@/components/main/Footer";
import AOSProvider from "@/components/AOSProvider";
import StarsCanvas from "@/components/main/StarBackground";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Habib Muhammad Rizki",
  description: "Generated by create next app",
  icons: {
    icon: "/habib.jpeg",
    shortcut: "/habib.jpeg",
    apple: "/habib.jpeg",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#030014] overflow-x-hidden relative`}
      >
        <StarsCanvas />
        <AOSProvider />
        <Navbar />
        <main className="relative z-10">{children}</main>
        <Toaster richColors position="top-right" />
        <Footer />
      </body>
    </html>
  );
}
